#!/usr/bin/python

# -*- coding: utf-8 -*-

# For better print formatting
from __future__ import print_function

# Imports
from pycompss.api.parallel import parallel
from pycompss.api.constraint import constraint
from pycompss.api.task import task
from pycompss.api.api import compss_barrier, compss_wait_on

import numpy as np


# TODO: Extend for non-square matrices. There is no size verifications.


def generate_matrix(m_size, b_size, block_type='random'):
    mat = []
    for i in range(m_size):
        mat.append([])
        for j in range(m_size):
            mat[i].append(create_block_wrapper(b_size, block_type))
    return mat


def generate_identity(m_size, b_size):
    mat = []
    for i in range(m_size):
        mat.append([])
        for j in range(0, i):
            mat[i].append(create_block_wrapper(b_size, block_type='zeros'))
        mat[i].append(create_block_wrapper(b_size, block_type='identity'))
        for j in range(i + 1, m_size):
            mat[i].append(create_block_wrapper(b_size, block_type='zeros'))
    return mat


def create_block_wrapper(b_size, block_type='random'):
    if block_type == 'zeros':
        block = []
    elif block_type == 'identity':
        block = []
    else:
        block = create_block(b_size)
    return [block_type, block]


@constraint(ComputingUnits="${ComputingUnits}")
@task(returns=list)
def create_block(b_size):
    return np.matrix(np.random.random((b_size, b_size)), dtype=np.double, copy=False)


# [COMPSs Autoparallel] Begin Autogenerated code
import math

from pycompss.api.api import compss_barrier, compss_wait_on, compss_open
from pycompss.api.task import task
from pycompss.api.parameter import *


@task(var2=IN, b_size=IN, returns=2)
def S1(var2, b_size):
    return qr(var2, b_size, transpose=True)


@task(var2=IN, q_act=IN, returns=1)
def S2(var2, q_act):
    return dot(var2, q_act, transpose_b=True)


@task(q_act=IN, var2=IN, returns=1)
def S3(q_act, var2):
    return dot(q_act, var2)


@task(sub_q=OUT)
def S4(sub_q):
    sub_q = [[np.matrix(np.array([0])), np.matrix(np.array([0]))], [np.
        matrix(np.array([0])), np.matrix(np.array([0]))]]


@task(var7=IN, var8=IN, b_size=IN, returns=6)
def S5(var7, var8, b_size):
    return little_qr(var7, var8, b_size, transpose=True)


@task(sub_q=IN, var3=IN, var4=IN, b_size=IN, returns=2)
def S6(sub_q, var3, var4, b_size):
    return multiply_blocked(sub_q, [[var3], [var4]], b_size)


@task(var3=IN, var4=IN, sub_q=IN, b_size=IN, returns=2)
def S7(var3, var4, sub_q, b_size):
    return multiply_blocked([[var3, var4]], sub_q, b_size, transpose_b=True)


def qr_blocked(a, m_size, b_size, overwrite_a=False):
    if __debug__:
        print('Matrix A:')
        print(a)
    q = generate_identity(m_size, b_size)
    if not overwrite_a:
        r = copy_blocked(a)
    else:
        r = a
    q_act = None
    if m_size >= 1:
        lbp = 0
        ubp = m_size - 2
        for t1 in range(0, m_size - 2 + 1):
            q_act, r[t1][t1] = S1(r[t1][t1], b_size)
            lbp = 0
            ubp = t1
            for t2 in range(0, t1 + 1):
                q[t2][t1] = S2(q[t2][t1], q_act)
            lbp = t1 + 1
            ubp = m_size - 1
            for t2 in range(t1 + 1, m_size - 1 + 1):
                q[t2][t1] = S2(q[t2][t1], q_act)
                r[t1][t2] = S3(q_act, r[t1][t2])
                S4(sub_q)
                sub_q[0][0], sub_q[0][1], sub_q[1][0], sub_q[1][1], r[t1][t1
                    ], r[t2][t1] = S5(r[t1][t1], r[t2][t1], b_size)
                lbp = 0
                ubp = t1
                for t3 in range(lbp, ubp + 1):
                    q[t3][t1], q[t3][t2] = S7(q[t3][t1], q[t3][t2], sub_q,
                        b_size)
                lbp = t1 + 1
                ubp = m_size - 1
                for t3 in range(lbp, ubp + 1):
                    r[t1][t3], r[t2][t3] = S6(sub_q, r[t1][t3], r[t2][t3],
                        b_size)
                    q[t3][t1], q[t3][t2] = S7(q[t3][t1], q[t3][t2], sub_q,
                        b_size)
        q_act, r[t1][t1] = S1(r[t1][t1], b_size)
        lbp = 0
        ubp = m_size - 1
        for t2 in range(0, m_size - 1 + 1):
            q[t2][t1] = S2(q[t2][t1], q_act)
    compss_barrier()
    if __debug__:
        q_res = join_matrix(compss_wait_on(q), b_size)
        r_res = join_matrix(compss_wait_on(r), b_size)
        print('Matrix Q:')
        print(q_res)
        print('Matrix R:')
        print(r_res)

# [COMPSs Autoparallel] End Autogenerated code


def copy_blocked(a, transpose=False):
    res = []
    for i in range(len(a)):
        res.append([])
        for j in range(len(a[0])):
            res[i].append(np.matrix([0]))
    for i in range(len(a)):
        for j in range(len(a[0])):
            if transpose:
                res[j][i] = a[i][j]
            else:
                res[i][j] = [a[i][j][0], a[i][j][1]]
    return res


def qr(mat, b_size, mode='reduced', transpose=False):
    q_aux, r_aux = qr_task(mat[1], b_size, mat[0], mode=mode, transpose=transpose)
    return ['random', q_aux], ['random', r_aux]


def qr_task(mat, b_size, block_type, mode='reduced', transpose=False):
    from numpy.linalg import qr

    if block_type == 'random':
        q_mat, r_mat = qr(mat, mode=mode)
    elif block_type == 'zeros':
        q_mat, r_mat = qr(np.matrix(np.zeros((b_size, b_size))), mode=mode)
    else:
        q_mat, r_mat = qr(np.matrix(np.identity(b_size)), mode=mode)
    if transpose:
        q_mat = np.transpose(q_mat)
    return q_mat, r_mat


def dot(a, b, transpose_result=False, transpose_b=False):
    if a[0] == 'zeros':
        return ['zeros', []]
    if a[0] == 'identity':
        if transpose_b and transpose_result:
            return b
        if transpose_b or transpose_result:
            return transpose_block(b)
        return b

    if b[0] == 'zeros':
        return ['zeros', []]
    if b[0] == 'identity':
        if transpose_result:
            return transpose_block(a)
        return a

    return ['random', dot_task(a[1], b[1], transpose_result=transpose_result, transpose_b=transpose_b)]


def dot_task(a, b, transpose_result=False, transpose_b=False):
    if transpose_b:
        b = np.transpose(b)
    if transpose_result:
        return np.transpose(np.dot(a, b))
    return np.dot(a, b)


def transpose_block(a):
    if a[0] == 'zeros' or a[0] == 'identity':
        return a
    return ['random', transpose_block_task(a[1])]


def transpose_block_task(mat):
    return np.transpose(mat)


def little_qr(a, b, b_size, transpose=False):
    sub_q00, sub_q01, sub_q10, sub_q11, aa, bb = little_qr_task(a[1], a[0], b[1], b[0], b_size, transpose)
    return ['random', sub_q00], ['random', sub_q01], ['random', sub_q10], ['random', sub_q11], ['random', aa], [
        'random', bb]


def little_qr_task(a_mat, a_block_type, b_mat, b_block_type, b_size, transpose=False):
    ent_a = [a_block_type, a_mat]
    ent_b = [b_block_type, b_mat]
    for mat in [ent_a, ent_b]:
        if mat[0] == 'zeros':
            mat[1] = np.matrix(np.zeros((b_size, b_size)))
        elif mat[1] == 'identity':
            mat[1] = np.matrix(np.identity(b_size))
    curr_a = np.bmat([[ent_a[1]], [ent_b[1]]])
    (sub_q, sub_r) = np.linalg.qr(curr_a, mode='complete')
    aa = sub_r[0:b_size]
    bb = sub_r[b_size:2 * b_size]
    sub_q = split_matrix(sub_q, 2)
    if transpose:
        return np.transpose(sub_q[0][0]), np.transpose(sub_q[1][0]), np.transpose(sub_q[0][1]), np.transpose(
            sub_q[1][1]), aa, bb
    else:
        return sub_q[0][0], sub_q[0][1], sub_q[1][0], sub_q[1][1], aa, bb


def multiply_blocked(a, b, b_size, transpose_b=False):
    if transpose_b:
        b_new = []
        for i in range(len(b[0])):
            b_new.append([])
            for j in range(len(b)):
                b_new[i].append(b[j][i])
        b = b_new
    c_mat = []
    for i in range(len(a)):
        c_mat.append([])
        for j in range(len(b[0])):
            c_mat[i].append(['zeros', []])
            for k in range(len(a[0])):
                c_mat[i][j] = multiply_single_block(a[i][k], b[k][j], c_mat[i][j], b_size, transpose_b=transpose_b)
    return c_mat


def multiply_single_block(a, b, c, b_size, transpose_b=False):
    if a[0] == 'zeros' or b[0] == 'zeros':
        return c
    c[1] = multiply_single_block_task(a[1], a[0], b[1], b[0], c[1], c[0], b_size, transpose_b=transpose_b)
    c = ['random', c[1]]
    return c


def multiply_single_block_task(a_mat, a_block_type, b_mat, b_block_type, c_mat, c_block_type, b_size,
                               transpose_b=False):
    a_fun = [a_block_type, a_mat]
    b_fun = [b_block_type, b_mat]
    if c_block_type == 'zeros':
        c_mat = np.matrix(np.zeros((b_size, b_size)))
    elif c_block_type == 'identity':
        c_mat = np.matrix(np.identity(b_size))

    if a_fun[0] == 'identity':
        if b_fun[0] == 'identity':
            b_fun[1] = np.matrix(np.identity(b_size))
        if transpose_b:
            aux = np.transpose(b_fun[1])
        else:
            aux = b_fun[1]
        c_mat += aux
        return c_mat

    if b_fun[0] == 'identity':
        c_mat += a_fun[1]
        return c_mat
    if transpose_b:
        b_fun[1] = np.transpose(b_fun[1])
    c_mat += (a_fun[1] * b_fun[1])

    return c_mat


def split_matrix(mat, m_size):
    b_size = len(mat) / m_size
    splitted_matrix = [[None for _ in range(m_size)] for _ in range(m_size)]
    for i in range(m_size):
        for j in range(m_size):
            splitted_matrix[i][j] = np.matrix(mat[i * b_size:(i + 1) * b_size, j * b_size:(j + 1) * b_size])
    return splitted_matrix


def blocked_transpose(mat):
    res = []
    for i in range(len(mat)):
        res.append([])
        for j in range(len(mat[0])):
            res[i].append(['random', np.matrix([0])])
    for i in range(len(mat)):
        for j in range(len(mat[0])):
            res[j][i] = transpose_block(mat[i][j])
    return res


def join_matrix(mat, b_size):
    joint_matrix = np.matrix([[]])
    for i in range(0, len(mat)):
        if mat[i][0][0] == 'zeros':
            mat[i][0][1] = np.matrix(np.zeros((b_size, b_size)))
        elif mat[i][0][0] == 'identity':
            mat[i][0][1] = np.matrix(np.identity(b_size))
        current_row = mat[i][0][1]
        for j in range(1, len(mat[i])):
            if mat[i][j][0] == 'zeros':
                mat[i][j][1] = np.matrix(np.zeros((b_size, b_size)))
            elif mat[i][j][0] == 'identity':
                mat[i][j][1] = np.matrix(np.identity(b_size))
            current_row = np.bmat([[current_row, mat[i][j][1]]])
        if i == 0:
            joint_matrix = current_row
        else:
            joint_matrix = np.bmat([[joint_matrix], [current_row]])
    return np.matrix(joint_matrix)


if __name__ == "__main__":
    # Import libraries
    import time

    # Parse arguments
    import sys

    args = sys.argv[1:]
    MSIZE = int(args[0])
    BSIZE = int(args[1])

    # Log arguments if required
    if __debug__:
        print("Running QR application with:")
        print(" - MSIZE = " + str(MSIZE))
        print(" - BSIZE = " + str(BSIZE))

    # Initialize matrix
    if __debug__:
        print("Initializing matrix")
    start_time = time.time()
    A = generate_matrix(MSIZE, BSIZE)
    compss_barrier()

    # Begin computation
    if __debug__:
        print("Performing computation")
    qr_start_time = time.time()
    qr_blocked(A, MSIZE, BSIZE)
    compss_barrier()
    end_time = time.time()

    # Log results and time
    if __debug__:
        print("Post-process results")
    total_time = end_time - start_time
    init_time = qr_start_time - start_time
    qr_time = end_time - qr_start_time

    print("RESULTS -----------------")
    print("MSIZE " + str(MSIZE))
    print("BSIZE " + str(MSIZE))
    print("DEBUG " + str(__debug__))
    print("TOTAL_TIME " + str(total_time))
    print("INIT_TIME " + str(init_time))
    print("QR_TIME " + str(qr_time))
    print("-------------------------")
