#!/usr/bin/python
# -*- coding: utf-8 -*-

# WARN: Should be generated by me and never written down
def matmul(mSize, nSize, kSize, bSize, debug):
        #######################
        # SCOP PARALLELIZED CODE
        #######################
        pass

