#!/usr/bin/python

# -*- coding: utf-8 -*-

# For better print formatting
from __future__ import print_function

# Imports
from pycompss.api.parallel import parallel
from pycompss.api.constraint import constraint
from pycompss.api.task import task
from pycompss.api.api import compss_barrier
from pycompss.api.api import compss_wait_on

import numpy as np


def generate_matrix(m_size, b_size):
    mat = []
    for i in range(m_size):
        mat.append([])
        for j in range(m_size):
            mb = create_block(b_size)
            mat[i].append(mb)

    return mat


@constraint(ComputingUnits="${ComputingUnits}")
@task(returns=list)
def create_block(b_size):
    block = np.array(np.random.random((b_size, b_size)), dtype=np.double, copy=False)
    mb = np.matrix(block, dtype=np.double, copy=False)
    return mb


# [COMPSs Autoparallel] Begin Autogenerated code
import math

from pycompss.api.api import compss_barrier, compss_wait_on, compss_open
from pycompss.api.task import task
from pycompss.api.parameter import *


@task(b_size=IN, returns=1)
def S1(b_size):
    return np.matrix(np.zeros((b_size, b_size)), dtype=float)


@task(b_size=IN, returns=1)
def S2(b_size):
    return np.matrix(np.zeros((b_size, b_size)), dtype=float)


@task(var1=IN, returns=1)
def S3(var1):
    return invert_triangular(var1, lower=True)


@task(aux=IN, var2=IN, var3=IN, returns=1)
def S4(aux, var2, var3):
    return multiply([1], aux, var2, var3)


@task(var1=IN, returns=1)
def S5(var1):
    return invert_triangular(var1, lower=False)


@task(var1=IN, aux=IN, returns=1)
def S6(var1, aux):
    return multiply([], var1, aux)


@task(var2=IN, aux2=IN, var3=IN, returns=1)
def S7(var2, aux2, var3):
    return dgemm(-1, var2, aux2, var3)


@task(var4=IN, returns=3)
def S8(var4):
    return custom_lu(var4)


@task(var1=IN, returns=1)
def S9(var1):
    return invert_triangular(var1, lower=False)


@task(var2=IN, var3=IN, aux=IN, returns=1)
def S10(var2, var3, aux):
    return multiply([0], var2, var3, aux)


@task(var1=IN, returns=1)
def S11(var1):
    return invert_triangular(var1, lower=True)


@task(aux=IN, var2=IN, var3=IN, returns=1)
def S12(aux, var2, var3):
    return multiply([1], aux, var2, var3)


def lu_blocked(a, m_size, b_size):
    if __debug__:
        print('Matrix A:')
        print(a)
    if len(a) == 0:
        return
    p_mat = [([np.matrix(np.zeros((b_size, b_size)), dtype=float)] * m_size
        ) for _ in range(m_size)]
    l_mat = [([None] * m_size) for _ in range(m_size)]
    u_mat = [([None] * m_size) for _ in range(m_size)]
    if m_size >= 2:
        lbp = 0
        ubp = m_size - 2
        for t1 in range(lbp, ubp + 1):
            lbv = t1 + 1
            ubv = m_size - 1
            for t2 in range(lbv, ubv + 1):
                l_mat[t1][t2] = S1(b_size)
                u_mat[t2][t1] = S2(b_size)
    compss_barrier()



    a[0][0] = compss_wait_on(a[0][0])
    p_mat[0][0], l_mat[0][0], u_mat[0][0] = custom_lu(a[0][0])
    aux = None
    aux2 = None
    if m_size >= 2:
        lbp = 1
        ubp = m_size - 1
        for t1 in range(lbp, ubp + 1):
            aux = S3(l_mat[0][0])
            u_mat[0][t1] = S4(aux, p_mat[0][0], a[0][t1])
    compss_barrier()


    if m_size >= 2:
        lbp = 1
        ubp = m_size - 2
        for t2 in range(lbp, ubp + 1):
            lbv = t2 + 1
            ubv = m_size - 1
            for t3 in range(lbv, ubv + 1):
                aux = S11(l_mat[t2][t2])
        lbv = 1
        ubv = m_size - 1
        for t4 in range(lbv, ubv + 1):
            a[t4][1] = S7(a[t4][1], aux2, u_mat[1 - 1][1])
        lbp = 2
        ubp = m_size - 1
        for t2 in range(lbp, ubp + 1):
            lbp = 1
            ubp = t2 - 1
            for t3 in range(1, t2 - 1 + 1):
                a[t4][1] = S7(a[t4][1], aux2, u_mat[1 - 1][1])
                u_mat[t3][t2] = S12(aux, p_mat[t3][t3], a[t3][t2])
                lbv = t3 + 1
                ubv = m_size - 1
                for t4 in range(lbv, ubv + 1):
                    a[t4][1] = S7(a[t4][1], aux2, u_mat[1 - 1][1])
            lbv = t2
            ubv = m_size - 1
            for t4 in range(lbv, ubv + 1):
                a[t4][1] = S7(a[t4][1], aux2, u_mat[1 - 1][1])
        lbp = 1
        ubp = m_size - 1
        for t2 in range(lbp, ubp + 1):
            lbv = 0
            ubv = t2 - 1
            for t3 in range(lbv, ubv + 1):
                l_mat[t2][t3] = S10(p_mat[t2][t2], a[t2][t3], aux)
        lbp = 1
        ubp = m_size - 1
        for t2 in range(lbp, ubp + 1):
            p_mat[t2][t2], l_mat[t2][t2], u_mat[t2][t2] = S8(a[t2][t2])
        lbp = 0
        ubp = m_size - 2
        for t2 in range(lbp, ubp + 1):
            lbv = t2 + 1
            ubv = m_size - 1
            for t3 in range(lbv, ubv + 1):
                aux = S9(u_mat[t2][t2])
        lbp = 1
        ubp = m_size - 1
        for t2 in range(lbp, ubp + 1):
            lbp = t2
            ubp = m_size - 1
            for t3 in range(t2, m_size - 1 + 1):
                lbv = t2
                ubv = m_size - 1
                for t4 in range(lbv, ubv + 1):
                    aux2 = S6(a[t3][t2 - 1], aux)
                    aux = S5(u_mat[t2 - 1][t2 - 1])
    compss_barrier()
    if __debug__:
        p_res = join_matrix(compss_wait_on(p_mat))
        l_res = join_matrix(compss_wait_on(l_mat))
        u_res = join_matrix(compss_wait_on(u_mat))
        print('Matrix P:')
        print(p_res)
        print('Matrix L:')
        print(l_res)
        print('Matrix U:')
        print(u_res)

# [COMPSs Autoparallel] End Autogenerated code


def invert_triangular(a, lower=False):
    from scipy.linalg import solve_triangular

    dim = len(a)
    identity = np.matrix(np.identity(dim))
    return solve_triangular(a, identity, lower=lower)


def multiply(inv_list, *args):
    # Base case checks
    assert (len(args) > 0)
    input_args = list(args)
    if len(input_args) == 1:
        return input_args[0]

    # Complex cases
    if len(inv_list) > 0:
        from numpy.linalg import inv
        for elem in inv_list:
            input_args[elem] = inv(args[elem])

    result = np.dot(input_args[0], input_args[1])
    for i in range(2, len(input_args)):
        result = np.dot(result, input_args[i])

    return result


def dgemm(alpha, a, b, c):
    a += (alpha * np.dot(b, c))

    return a


def custom_lu(a):
    from scipy.linalg import lu
    return lu(a)


def join_matrix(mat):
    joint_matrix = np.matrix([[]])
    for i in range(0, len(mat)):
        current_row = mat[i][0]
        for j in range(1, len(mat[i])):
            current_row = np.bmat([[current_row, mat[i][j]]])
        if i == 0:
            joint_matrix = current_row
        else:
            joint_matrix = np.bmat([[joint_matrix], [current_row]])

    return np.matrix(joint_matrix)


if __name__ == "__main__":
    # Import libraries
    import time

    # Parse arguments
    import sys

    args = sys.argv[1:]
    MSIZE = int(args[0])
    BSIZE = int(args[1])

    # Log arguments if required
    if __debug__:
        print("Running LU application with:")
        print(" - MSIZE = " + str(MSIZE))
        print(" - BSIZE = " + str(BSIZE))

    # Initialize matrix
    if __debug__:
        print("Initializing matrix")
    start_time = time.time()
    A = generate_matrix(MSIZE, BSIZE)
    compss_barrier()

    # Begin computation
    if __debug__:
        print("Performing computation")
    lu_start_time = time.time()
    lu_blocked(A, MSIZE, BSIZE)
    compss_barrier()
    end_time = time.time()

    # Log results and time
    if __debug__:
        print("Post-process results")
    total_time = end_time - start_time
    init_time = lu_start_time - start_time
    lu_time = end_time - lu_start_time

    print("RESULTS -----------------")
    print("VERSION AUTOPARALLEL")
    print("MSIZE " + str(MSIZE))
    print("BSIZE " + str(MSIZE))
    print("DEBUG " + str(__debug__))
    print("TOTAL_TIME " + str(total_time))
    print("INIT_TIME " + str(init_time))
    print("LU_TIME " + str(lu_time))
    print("-------------------------")
