#!/usr/bin/python                                                                                                                                                                                                                                                              
# -*- coding: utf-8 -*-

# WARN: Should be generated by pluto and never written to the user file
def matmul(mSize, nSize, kSize, bSize, debug):
        # Initialize
        a = initialize(mSize, nSize, bSize, True)
        b = initialize(nSize, kSize, bSize, True)
        c = initialize(mSize, kSize, bSize, False)

        # Debug
        if debug:
                print "Matrix A:"
                print a
                print "Matrix B:"
                print b
                print "Matrix C:"
                print c

        # Perform computation
        # c = a*b
        # Start of CLooG code
        if mSize >= 1 and nSize >= 1 and kSize >=1:
                #pragma omp parallel for
                for i in range(mSize):
                        for j in range(kSize):
                                for k in range(nSize):
                                        c[i][j] += a[i][k] * b[k][j]
        # End of CLooG code

        # Debug
        if debug:
                print "Matrix C:"
                print c

        # Result
        return c

